spin_manifest_version = 2

[application]
name = "cloud_start"
version = "0.1.0"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Your first Fermyon Cloud application"

[[trigger.http]]
route = "/..."
component = "cloudstart"

[component.cloudstart]
source = "target/wasm32-wasi/release/cloud_start.wasm"
[component.cloudstart.build]
command = "cargo build --target wasm32-wasi --release"
